### ISSUE TITLE
do you intend to continue this project?

### ISSUE THREAD

**Issue by giovannism20** [IonicaBizau/VimOS#8]
I think vim it's a great editor and I think that more people should know him too, what do you think continue with the project? I was only a little lost in "where to begin the [" installation "]...

**Sorry if there are any errors in the structure of the issue, I just did not see anything in the contribution talking about issues structures**

**Comment by IonicaBizau** [comment]
This project is an experiment. If you have any suggestions, feel free to contribute! 😁

**Comment by giovannism20** [comment]
Sure! :octocat:
